### PR TITLE
source volume

### PR DESCRIPTION
**Pull request by jdelkins**
Add api functions to manipulate the default source (volume, mute)

### CODE REVIEW

**Comment by lawl** [comment]
sorry for taking so long, i was - uh - busy with stuff.  This API is a bit higher level than i'd like to be. you query serverinfo etc to figure out the source to use automatically.

this library is intended to operate at a lower level. rule of thumb: 1 API call = 1 RCP. thus the source should be specified by the user here, without any magic.

**Comment by jdelkins** [comment]
Hi. I don't disagree philosophically, but I was trying to parallel, as much as possible, existing functions exposed in `volume.go`. E.g. `SourceVolume()` takes exactly the approach that `Volume()` does. Would you prefer to rework the whole lot (which would be a breaking change) or take a different approach only for incremental APIs? Or, if now's not the right time, happy to close this PR and come back later...

**Comment by jdelkins** [comment]
On a second look, I did see one difference `SetSourceVolume()`, addressed in the above commit.

**Comment by lawl** [comment]
Hi I must admit i didnt look that deeply it. If you dont mind, later would be a better time.

**Comment by jdelkins** [comment]
Sure. I might rebase to github.com/mafik/pulseaudio and see if they want to expand the volume API in this way.

**Pull request closed without merging**
