### PR TITLE
Look for the cookie in the config

### PR DESCRIPTION
**Pull request by iptq**
My pulseaudio is configured through the config, but this library isn't picking it up. I just patched the cookiePath function to actually check for that by reading the config.

### CODE REVIEW

**Comment by lawl** [comment]
This pulls in way too many new dependencies. Please remove them, finding a config file on the FS shouldn't require pulling in that much code.

**Comment by lawl** [comment]
Also please remove the renaming of variables and reformatting to make the diff readable.

**Comment by iptq** [comment]
Oh wow that _is_ quite a lot. Does go modules have some concept of dev dependencies? It seems all of those dependencies are pulled in by the assert package which is only used for testing in the xdg package.

**Comment by lawl** [comment]
Not that i know of, but i also wouldn't take them as dev dependencies. As written in the readme, maintenance of this lib from my side is very limited, so if you'd prefer to not make these changes, i suggest to maintain your own fork.

**Comment by iptq** [comment]
Sounds like a good idea, I will do that instead

**Pull request closed without merging**
